version: '3.2'
services:
  server:
    image: amcolash/kindle-calendar
    build: ./
    container_name: kindle-calendar
    restart: unless-stopped
    network_mode: 'host'
    env_file: .env
    # cap_add:
    #   - SYS_ADMIN
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - ./.cert:/usr/src/app/.cert:ro
      - ./settings.json:/usr/src/app/settings.json
