version: '3.2'
services:
  server:
    image: amcolash/kindle-calendar
    build: ./
    container_name: kindle-calendar
    restart: unless-stopped
    network_mode: 'host'
    env_file: ./server/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server/.cert:/usr/src/app/.cert:ro
      - ./server/settings.json:/usr/src/app/settings.json
